import type { SceneItem } from "./types";

export const ABANDONED_WAREHOUSE_ITEMS: SceneItem[] = [
  {
    id:          "taosheng_warehouse",
    name:        "陶生",
    shortDesc:   "在附近工作的工人",
    inspectText: "他在倉庫外側做一些看起來是日常維護的工作，但他做得很慢，比正常工作速度慢很多，像是在磨時間，或者在等什麼。你走近的時候，他先聽到了腳步聲，停下手上的事，轉過來。他的眼神有一點不對——不是防備，是那種你見過什麼但說不清楚你見過什麼的茫然。",
    type:        "npc",
    icon:        "👷",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "倉庫外側",
    npcId:       "taosheng",
  },
  {
    id:          "zhuanghe_warehouse",
    name:        "莊河",
    shortDesc:   "在做記錄的人",
    inspectText: "他站在倉庫門口，手裡拿著一個小本子，在寫什麼。你走過去，他沒有停下，繼續寫完最後一行，才抬頭看你。「你也來查的。」不是問句。他把本子收起來，看了一眼倉庫的門，然後看回你。「我先來的，所以我先說規矩：進去之前，想好你如果找到了什麼，你打算怎麼辦。」",
    type:        "npc",
    icon:        "🕵️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "倉庫入口",
    npcId:       "zhuanghe",
  },
  {
    id:          "shipping_manifest",
    name:        "貨物清單",
    shortDesc:   "釘在木板上的舊清單",
    inspectText: "釘在牆壁木板上，邊角翹起來，有幾張已經爛掉了。你找到最近的幾張，日期是三個月前。清單上的貨物欄大部分是一般建材，但有一行你注意到了：「特殊設備 × 1，收件人：P.R.O.C.，請勿開箱」。這個縮寫你在別的地方看過，或者你會看到。那一行旁邊有人用紅筆畫了一個問號。",
    type:        "item",
    icon:        "📦",
    pickable:    true,
    inventoryEntry: {
      itemId:      "warehouse_manifest",
      name:        "倉庫貨物清單",
      description: "三個月前的進貨記錄，含一筆「特殊設備 × 1，收件人：P.R.O.C.，請勿開箱」，旁邊有紅筆問號。P.R.O.C. 與 BTMA 機構受限部門縮寫相符。",
      icon:        "📦",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "牆壁木板",
  },
  {
    id:          "hidden_room",
    name:        "隱藏小室",
    shortDesc:   "倉庫深處的門",
    inspectText: "貨架後面，門的顏色和牆壁幾乎一樣，不是偽裝，是油漆的時候刷過去了。你推開門，裡面是一個大概三坪的空間，空的，但地板上有幾個矩形的深色痕跡——是某種重物放過的痕跡，放了很久，然後被移走了。角落有一個沒帶走的繩結，很粗的繩子，打成一個你說不出名字的結。",
    type:        "clue",
    icon:        "🚪",
    pickable:    false,
    triggersClue: true,
    clueContent: "廢棄倉庫深處存在隱密小室，地板留有重物長期擺放痕跡及特殊繩結。空間特徵符合臨時羈押或設備存放用途，與碼頭失蹤路線交叉點吻合。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "倉庫深處貨架後",
  },
  {
    id:          "blood_residue",
    name:        "地板上的殘留",
    shortDesc:   "角落的深色痕跡",
    inspectText: "你蹲下來，光線不夠，你用手機的燈照。深褐色，面積不大，大概是一個手掌的範圍，邊緣已經乾了很久，但中心還有點深。你不能確定這是什麼，但你能確定的是，這個地方有人試圖清理過——周圍的地板比其他地方乾淨，留下來的那一塊是清理之後漏掉的。",
    type:        "clue",
    icon:        "🔴",
    pickable:    false,
    triggersClue: true,
    clueContent: "廢棄倉庫角落發現深褐色殘留物，周圍有刻意清理痕跡，但清理不完整。殘留位置與隱密小室相鄰。物質性質待確認，但排除偶然遺留。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "倉庫角落",
  },
  {
    id:          "coded_graffiti",
    name:        "暗語塗鴉",
    shortDesc:   "牆上的字",
    inspectText: "在牆壁最靠近地板的位置，字很小，用很細的簽字筆寫的，如果不是特別去找你不會看見。大部分是符號和數字，但有幾個字你認識：「明後必收」「不要讓他看見」「C區是陷阱」。最後一行只有兩個字，但被塗掉了，塗掉的人用了不同的筆——比其他字跡更新。",
    type:        "item",
    icon:        "✍️",
    pickable:    true,
    inventoryEntry: {
      itemId:      "coded_graffiti_note",
      name:        "倉庫牆面暗語",
      description: "倉庫牆腳的細小字跡，包含「明後必收」「C區是陷阱」等語句。最後一行被人用不同的筆塗抹覆蓋，塗改時間晚於原始書寫。",
      icon:        "✍️",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "倉庫牆壁近地面處",
  },
  {
    id:          "broken_cctv",
    name:        "損壞的監視器",
    shortDesc:   "天花板上的攝影機",
    inspectText: "天花板的鋼架上，有一個監視器的支架，但攝影機的部分已經不在了——連螺絲都卸了，不是摔壞，是被人拆走的。電線的末端被膠帶纏住，防止接觸。你看了一下周圍，別的地方沒有其他監視器，只有這一個的支架在。就是這一個，有人特意來拆掉的。",
    type:        "environment",
    icon:        "📷",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "天花板鋼架",
  },
];
