import type { SceneItem } from "./types";

export const BAI_QIU_PHARMACY_ITEMS: SceneItem[] = [
  {
    id:          "baiqiu_counter",
    name:        "白秋",
    shortDesc:   "藥局藥師",
    inspectText: "她站在調劑台後面，動作很小，很精準。藥罐在她手裡沒有多餘的聲音。你走進來的時候，她沒有抬頭，但你確定她已經知道你在哪裡。她什麼都不主動說，但她也沒有讓你等——她只是在等你先開口。",
    type:        "npc",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "調劑台後方",
    npcId:       "baiqiu",
  },
  {
    id:          "zhengbo_pharmacy",
    name:        "鄭博",
    shortDesc:   "正在查記錄的客人",
    inspectText: "他不是來買藥的。他站在陳列架旁邊，手裡拿著一個什麼，但他的眼睛在看別的地方。白秋給他遞了一小袋東西，兩個人沒有說話。你進來的時候，他把手裡那個東西放進口袋，轉過來看你，眼神像是在算你值不值得信。",
    type:        "npc",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "陳列架旁",
    npcId:       "zhengbo",
  },
  {
    id:          "prescription_log",
    name:        "處方記錄本",
    shortDesc:   "手寫處方總表",
    inspectText: "記錄本的紙已經有點毛邊，但每一條都寫得工整。你翻到最近三個月的頁面，一個模式從數字裡浮出來：有七個不同的客戶，在相差不超過兩天的時間段裡，分別來買了同一種藥——用途是「感官抑制，情緒穩定」，適應症欄位裡統一寫的是「相位適應不良」。七個人。你在某份失蹤名單上至少看過其中三個名字。",
    type:        "clue",
    icon:        "▣",
    pickable:    false,
    triggersClue: true,
    clueContent: "藥局處方記錄顯示：七名顧客在近期集中購買相同的感官抑制劑（相位適應不良）。其中至少三人確認列於失蹤名單。失蹤者在消失前曾集中服用同類藥物。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "調劑台邊",
  },
  {
    id:          "suppressed_shipment",
    name:        "壓下去的進貨單",
    shortDesc:   "被另一疊紙壓著的文件",
    inspectText: "壓在日曆底下，不是不見了，是刻意放在一個不顯眼的地方。進貨日期比帳本記錄的早了四天，藥品名稱有一部分被塗掉了，塗的方式不像是錯字修改，更像是不想讓你看見。還留著的數字是某種劑量換算，你看不懂，但你知道這個量不對。",
    type:        "item",
    icon:        "▣",
    pickable:    true,
    inventoryEntry: {
      itemId:      "suppressed_shipment_doc",
      name:        "異常進貨單",
      description: "日期比帳面記錄提早四天的進貨文件，藥品名稱部分遭塗抹。殘留劑量換算數值異常，疑為專業用途藥物的私下進口紀錄。",
      icon:        "▣",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "日曆底下",
  },
  {
    id:          "security_camera",
    name:        "監視器",
    shortDesc:   "角落的攝影機",
    inspectText: "掛在牆角，鏡頭角度朝向門口。紅色指示燈沒有亮。你仔細看，發現鏡頭後面的接線被剪斷了——不是鬆脫，是用剪刀剪的，截面很整齊。白秋沒有解釋，你也沒有問。但你注意到剪斷的時間不算久，線頭還沒有氧化變黃。",
    type:        "environment",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "牆角",
  },
  {
    id:          "hidden_counter_memo",
    name:        "收銀台暗格",
    shortDesc:   "檯面板下的夾層",
    inspectText: "是那種只有你趴下來才看得到的角度。夾層很淺，只能放幾張紙。裡面有一張對折的紙，字跡不是白秋的——太用力，筆跡有點歪。寫的是一個地址和一個時間：「碼頭舊倉儲C區，周四11後」。時間比上週還早，說明那次的約已經過了。但紙還在。",
    type:        "item",
    icon:        "▣",
    pickable:    true,
    inventoryEntry: {
      itemId:      "counter_hidden_memo",
      name:        "隱藏便條紙",
      description: "藏在藥局收銀台夾層的紙條，非白秋筆跡：「碼頭舊倉儲C區，周四11後」。日期已過，但紙條仍在。連結碼頭廢棄倉庫。",
      icon:        "▣",
    },
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "收銀台夾層",
  },
  {
    id:          "customer_names",
    name:        "常客記名卡",
    shortDesc:   "舊式顧客名卡",
    inspectText: "一疊印著格線的小卡，是白秋自己寫的，不是電腦印的。每張卡上有名字、聯絡電話、常用藥物。你翻到靠後面的幾張，有三張的姓名欄被劃了一條橫線——不是更正的那種，是某種終結的方式。三個名字，你在失蹤名單上全部都找得到。",
    type:        "clue",
    icon:        "▣",
    pickable:    false,
    triggersClue: true,
    clueContent: "藥局常客名卡中有三名顧客被用橫線劃去——三人均列於失蹤名單。白秋早在官方公告前已知悉這三人失蹤，或主動記錄了這件事。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "調劑台抽屜",
  },
];
