import type { SceneItem } from "./types";

export const BTMA_LOBBY_ITEMS: SceneItem[] = [
  {
    id:          "it_btma",
    name:        "謝先生",
    shortDesc:   "大廳等待區的人",
    inspectText: "他坐在等待區的椅子上，但他的姿勢告訴你他已經等了很久，不是今天才等的那種久。他穿的衣服和大廳裡其他人不一樣——不是正式，也不是休閒，是一種剛好讓你無法歸類的穿法。他沒有拿訪客證，但保安也沒有去問他。你不確定他是屬於這裡的人，還是這裡的人假裝他不存在。",
    type:        "npc",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "大廳等待區",
    npcId:       "it",
  },
  {
    id:          "yushuang_btma",
    name:        "余霜",
    shortDesc:   "熟門熟路的訪客",
    inspectText: "她在辦理訪客證的時候，那個前台工作人員認識她——你從他們不需要確認身份的方式判斷的。她拿到通行證，往裡面走，沒有看左右，像是走過很多次的路。然後她轉頭，看到你，停了半秒，繼續走。那半秒你記住了。",
    type:        "npc",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "訪客登記台旁",
    npcId:       "yushuang",
  },
  {
    id:          "signin_log",
    name:        "訪客簽到紀錄",
    shortDesc:   "前台的訪客簿",
    inspectText: "前台的訪客簿用的是電子平板，但旁邊還有一本手寫的備用記錄，字跡各異。你翻到最近兩週，在第十四號案發日期的那一頁，有一個名字你沒有見過，但它下面的分機號碼你記下來了。再往後翻幾頁，同一個名字出現了三次，每次都在深夜時段，每次都沒有備注是拜訪哪個部門。",
    type:        "clue",
    icon:        "▣",
    pickable:    false,
    triggersClue: true,
    clueContent: "BTMA 機構訪客記錄中，案發日期當晚有一名不明訪客深夜進入，無部門備注，此後兩週內同名訪客再次出現三次。訪客姓名不在任何已知人物名單中，分機號碼指向受限樓層。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "前台登記台",
  },
  {
    id:          "directory_board",
    name:        "機構部門索引板",
    shortDesc:   "大廳左側的部門指引",
    inspectText: "標準的企業風格，黑底白字，部門名稱一列一列。大部分你看得懂：行政、財務、公共事務、技術支援。但有一個部門名稱只有英文縮寫——「P.R.O.C.」——沒有中文翻譯，也沒有標示樓層。你在電梯按鈕上沒有找到這個部門對應的樓層。它沒有在任何公開資料裡出現過。",
    type:        "environment",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: true,
    position:    "大廳左側",
  },
  {
    id:          "restricted_badge",
    name:        "掉落的通行證",
    shortDesc:   "椅子縫隙裡的訪客證",
    inspectText: "夾在等待區椅子的縫隙裡，像是不小心掉進去又沒人發現的。訪客證的照片欄是空的，名字欄上是那個你在訪客簿裡看到的名字。有效期限是今天。背面有一個印章，機構名稱縮寫是「P.R.O.C.」——就是剛才那個沒有樓層的部門。",
    type:        "item",
    icon:        "▣",
    pickable:    true,
    inventoryEntry: {
      itemId:      "btma_restricted_badge",
      name:        "PROC 部門通行證",
      description: "無照片的訪客通行證，對應訪客記錄中的不明訪客姓名。背面印有「P.R.O.C.」部門章——在 BTMA 官方索引中此部門無樓層登記。今日有效。",
      icon:        "▣",
    },
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "等待區椅縫",
  },
  {
    id:          "internal_memo",
    name:        "流出的內部備忘錄",
    shortDesc:   "廢紙桶旁的文件",
    inspectText: "沒有完全投進去，搭在桶緣上。你把它拿起來，是一份單頁的備忘錄，抬頭是「P.R.O.C. 內部評估——第五輪，結案前確認清單」。正文是一個打勾的清單，十三個項目，十三個都有打勾。第十四個項目旁邊的格子是空的，沒有打勾。備忘錄日期是第十四號案發的前兩天。",
    type:        "clue",
    icon:        "▣",
    pickable:    false,
    triggersClue: true,
    clueContent: "BTMA 內部備忘錄顯示「P.R.O.C.」部門進行「結案前確認清單」，共十四項，前十三項均已完成。第十四項未打勾——對應第十四號失蹤案。失蹤事件可能為有計劃的系統性行動。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "廢紙桶旁",
  },
  {
    id:          "cctv_monitor_room",
    name:        "監控室",
    shortDesc:   "走廊盡頭的小房間",
    inspectText: "門是開著的，但裡面沒有人。六個螢幕，四個是黑的，兩個還在顯示走廊的即時畫面。你走進去，看到桌上有一個已經播完的 USB 槽還插著，旁邊有一張黃色便條紙，上面只有一個時間：22:40。你在陳姐麵館的收銀台也看過這個時間。",
    type:        "environment",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: true,
    position:    "走廊盡頭監控室",
  },
];
