import type { SceneItem } from "./types";

export const CHEN_JIE_NOODLES_ITEMS: SceneItem[] = [
  {
    id:          "chen_jie",
    name:        "陳姐",
    shortDesc:   "麵館老闆娘",
    inspectText: "她在收銀台後面，背靠著牆，雙手放在檯面上。動作很少，但眼神不停在移動。每個進來的客人她都掃一眼，就像在做某種無聲的分類。她看了你一次。只有一次，但你覺得她已經知道你為什麼來了。",
    type:        "npc",
    icon:        "👩",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "收銀台後方",
    npcId:       "chen_jie",
  },
  {
    id:          "zhengbo",
    name:        "鄭博",
    shortDesc:   "角落常客",
    inspectText: "他坐在最靠窗的位置，那個位置可以看見門口，也可以看見後廚。茶杯裡的茶已經涼了，他沒有喝。他的手機螢幕朝下放在桌上，像是刻意擋住什麼。你走過去的時候，他沒有抬頭，但你注意到他的手指輕輕彈了一下桌面。",
    type:        "npc",
    icon:        "🧔",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "角落靠窗的座位",
    npcId:       "zhengbo",
  },
  {
    id:          "baiqiu",
    name:        "白秋",
    shortDesc:   "藥局來的身影",
    inspectText: "她不是麵館的常客，你從她找位子的方式就看出來了。最後選了一張離門口最近的桌子，衣服上還有藥局的消毒水氣味。她點了一碗什麼，但一口也沒動。偶爾往窗外看，確認某個位置，然後又把目光收回來。",
    type:        "npc",
    icon:        "👩‍⚕️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "從藥局過來的身影",
    npcId:       "baiqiu",
  },
  {
    id:          "newspaper",
    name:        "吧台舊報紙",
    shortDesc:   "泛黃報紙",
    inspectText: "壓在鹽罐底下，邊角已經因為油煙變得有些透明。三個月前的日期，第七版被人翻開放著。一篇關於失蹤者家屬的採訪，有個人用原子筆在其中一段話旁邊畫了一個圈——不是隨手的那種，是仔細畫的。",
    type:        "item",
    icon:        "📰",
    pickable:    true,
    inventoryEntry: {
      itemId:      "newspaper_clipping",
      name:        "泛黃的報紙",
      description: "一份三個月前的報紙，第七版有一篇失蹤者家屬的採訪被人用原子筆圈起來。圈住的那段話是：「他失蹤那天，有人打電話到家裡，說他下班後去了中城區。」",
      icon:        "📰",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "吧台",
  },
  {
    id:          "wall_photo",
    name:        "牆上合照",
    shortDesc:   "褪色舊照片",
    inspectText: "相框有點歪，但沒有人去扶正它。照片裡的陳姐比現在年輕很多，站在一個穿西裝的男人旁邊，兩個人都在笑。那個男人的臉被人用細簽字筆打了叉，墨水已經很舊了，叉打得很重，紙都有點皺。你再看一次，那個男人的臉，你在某個失蹤名單上見過類似的輪廓。",
    type:        "environment",
    icon:        "🖼️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "牆上",
  },
  {
    id:          "forgotten_coat",
    name:        "角落外套",
    shortDesc:   "遺落的外套",
    inspectText: "掛在最裡面那個角落的椅背上，像是被忘記的。布料是深色的，品質不錯，不是這一帶的人平時穿的款式。下擺有一個鈕扣只剩半顆，掛著快要掉的樣子。領口內側有人用白色麥克筆寫了兩個字母——不是名字，是縮寫。",
    type:        "item",
    icon:        "🧥",
    pickable:    true,
    inventoryEntry: {
      itemId:      "coat_button",
      name:        "外套鈕扣",
      description: "從角落那件外套的領口找到的鈕扣，上面有人用白色麥克筆寫了字母縮寫「K.L.」。不是常見的中文姓名縮寫方式。",
      icon:        "🧥",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "角落椅子",
  },
  {
    id:          "floor_footprints",
    name:        "地板鞋印",
    shortDesc:   "可疑鞋印",
    inspectText: "廚房和後門之間的地板比其他地方乾淨，但有一排鞋印沒被拖乾淨。尺寸大，步距寬，不像是後廚人員走路的節奏。更奇怪的是方向：那雙鞋是從後門進來的，不是出去的。後門通往哪裡，你還不知道。",
    type:        "clue",
    icon:        "👣",
    pickable:    false,
    triggersClue: true,
    clueContent: "陳姐麵館後門方向有不明人士留下的鞋印，進入方向而非離開方向，步距與後廚員工不符。後門連接中城舊巷。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "廚房走道",
  },
  {
    id:          "counter_note",
    name:        "收銀台便條",
    shortDesc:   "撕半的便條",
    inspectText: "壓在收銀機底盤角落，只剩半張，另一半被撕走了。還留下來的那半張寫著一個時間：22:40。時間下面是幾個字的後半段，前面的字已經不見了，只剩下「……回來」。墨水是藍色原子筆，字跡和桌上那份報紙圈起來的是同一支筆。",
    type:        "clue",
    icon:        "📝",
    pickable:    false,
    triggersClue: true,
    clueContent: "收銀台發現時間標記「22:40……回來」的半張便條，字跡與報紙上的圈記相符，疑為同一人所寫。22:40 與第十二號失蹤案的最後目擊時間吻合。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "收銀台",
  },
  {
    id:          "menu_back",
    name:        "菜單背面塗鴉",
    shortDesc:   "菜單上的字",
    inspectText: "菜單背面本來是空白的，有人用鉛筆密密麻麻寫了一些東西，後來被自己擦掉了，但用側光照就能看到壓痕。能辨認出的有幾個詞：「碼頭」、「周三」、「不要問他」。最後一行只有四個字，壓痕最深：「已經太晚」。",
    type:        "item",
    icon:        "✏️",
    pickable:    true,
    inventoryEntry: {
      itemId:      "menu_notes",
      name:        "菜單背面塗鴉",
      description: "菜單背面被擦掉的鉛筆字跡，側光下可見壓痕：「碼頭」、「周三」、「不要問他」，最後一行：「已經太晚」。筆跡細小，像是一個人在等待時寫的。",
      icon:        "✏️",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "桌上",
  },
];
