import type { SceneItem } from "./types";

export const CRIME_SCENE_ITEMS: SceneItem[] = [
  {
    id:          "hanzhuo",
    name:        "韓卓",
    shortDesc:   "在記錄的人",
    inspectText: "他在封鎖線外側緩慢移動，手裡拿著一個小本子，每隔幾步停下來寫幾個字。他的動作有一種習慣性的精確，不像是第一次做這種事。你靠近的時候，他沒有停下筆，只是說：「不是警察的話，封鎖線外面站。」",
    type:        "npc",
    icon:        "🕵️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "封鎖線外側",
    npcId:       "hanzhuo",
  },
  {
    id:          "linzhixia",
    name:        "林知夏",
    shortDesc:   "蹲在角落的人",
    inspectText: "蹲在最靠牆的角落，膝蓋幾乎貼著地面，寫字的速度很快。她用的是鉛筆，本子上密密麻麻全是圖和箭頭。你沒辦法看清楚她寫的是什麼，但能看到她圈起了某個位置——那個位置不在粉筆輪廓裡，比輪廓往右移了一步。",
    type:        "npc",
    icon:        "👩‍🔬",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "牆角",
    npcId:       "linzhixia",
  },
  {
    id:          "police_tape",
    name:        "黃色封鎖線",
    shortDesc:   "案發封鎖帶",
    inspectText: "帶子拉得有點鬆，右邊那根柱子快要倒了，但沒有人去修。膠帶是標準的警用規格，印著「POLICE LINE DO NOT CROSS」，中英文交錯。有一段帶子被什麼東西摩擦過，表面有微細的纖維，不是帆布，更細，更柔，像是某種特殊用料的衣物留下的。",
    type:        "environment",
    icon:        "🚧",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "現場外圍",
  },
  {
    id:          "chalk_outline",
    name:        "粉筆輪廓",
    shortDesc:   "奇怪的輪廓",
    inspectText: "輪廓畫在地面，但有問題。肩寬的標記比通常的失蹤者描述窄至少十公分，頭部位置明顯偏低。這個輪廓不是按照失蹤者的體型畫的，或者說，這個輪廓標記的，根本不是同一個人的位置。第一個察覺這件事的人，已經停止調查這個案子了。",
    type:        "clue",
    icon:        "🔍",
    pickable:    false,
    triggersClue: true,
    clueContent: "案發現場粉筆輪廓的體型標記與失蹤者描述不符：肩寬偏窄、身高偏低，疑似記錄了另一名未知人員的位置，或現場被刻意移動過。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "現場中央",
  },
  {
    id:          "wall_scratches",
    name:        "牆上抓痕",
    shortDesc:   "細密抓痕",
    inspectText: "牆壁的粗糙面上有幾道細痕，高度大約在腰部，不是手，是指甲，而且方向是從右往左，像是有人靠著牆試圖移動。指甲的角度說明這個人當時是蹲著或半蹲的。牆面這一段有一點點什麼東西乾掉了，呈現出一種不均勻的光澤，和普通灰塵不同。",
    type:        "clue",
    icon:        "🔍",
    pickable:    false,
    triggersClue: true,
    clueContent: "案發現場牆壁腰部高度發現指甲抓痕，方向由右至左，顯示有人以蹲姿試圖沿牆移動。痕跡旁有不明乾燥物質，疑似化學殘留。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "東側牆面",
  },
  {
    id:          "broken_camera",
    name:        "壞掉的監視器",
    shortDesc:   "損毀監視器",
    inspectText: "監視器的鏡頭朝著牆壁，不是朝向現場。有人把它轉了方向，但沒有完全拔掉，像是既想破壞又不想讓人一眼看出被動過手腳。主機的指示燈是綠色的，還在運作，只是拍不到任何有意義的畫面。這台機器，在事情發生的那個夜晚，什麼都沒有記錄到。",
    type:        "environment",
    icon:        "📷",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "角落高處",
  },
  {
    id:          "glasses_shard",
    name:        "碎眼鏡片",
    shortDesc:   "鏡框碎片",
    inspectText: "在封鎖線內側的邊緣，一塊透明的鏡片碎片，半埋在地縫裡。鏡框的殘留顯示是左半邊，金屬框，老款式。度數很深，這種度數的人不可能不認得自己的眼鏡。失蹤者名單上有幾個人的描述提到了近視，但這種度數，只有一個人。",
    type:        "item",
    icon:        "🔭",
    pickable:    true,
    inventoryEntry: {
      itemId:      "glasses_shard",
      name:        "碎裂的鏡片",
      description: "鏡框左半邊的碎片，老款金屬鏡框，度數極深。失蹤者名單中，林文哲曾在中城眼科配過-9.5度的近視眼鏡，鏡框款式與此吻合。",
      icon:        "🔭",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "地面縫隙",
  },
  {
    id:          "cloth_strip",
    name:        "沾色布條",
    shortDesc:   "染色布料",
    inspectText: "布條卡在牆面粗糙紋路裡，寬度大約三公分，顏色是米白底，上面有一種不均勻的藍綠色漬，不是泥土，不是油，是某種化學物質。漬的邊緣有一點結晶化，像是液體乾掉之後留下的。布的材質是醫用等級的棉，這個城市能生產這種布料的工廠，不超過三家。",
    type:        "item",
    icon:        "🧵",
    pickable:    true,
    inventoryEntry: {
      itemId:      "cloth_strip_stained",
      name:        "沾染藍綠色的布條",
      description: "醫用棉布條，沾有藍綠色化學物質，邊緣有結晶殘留。成分待分析，但氣味近似某種鎮定或麻醉類藥物的溶劑。",
      icon:        "🧵",
    },
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "牆面縫隙",
  },
  {
    id:          "chemical_smell",
    name:        "奇怪的氣味",
    shortDesc:   "揮之不去的氣味",
    inspectText: "你站在現場正中間，有一瞬間聞到什麼東西。不重，但是很特別，帶一點甜，又帶一點刺，像是某種揮發性的溶劑。你閉眼再深吸一口，氣味已經消散了，只剩下巷子裡的潮濕和銅鏽。但那一瞬間的甜味是真實的，你之前在某個地方聞過，就在記憶的邊緣，你沒辦法說清楚在哪裡。",
    type:        "environment",
    icon:        "💨",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "現場中央",
  },
  {
    id:          "needle_mark",
    name:        "注射器痕跡",
    shortDesc:   "針頭留下的孔",
    inspectText: "在靠牆的木質電箱蓋上，有幾個細小的圓孔，直徑大約一毫米，深度均勻。不是蟲洞，角度太一致了，是針頭留下的。孔的排列有某種規律，像是試了幾次才找到正確的位置。電箱連接著整條巷子的監控電路。如果有人知道怎麼用這個方法讓監控系統出現幾秒鐘的空白，他們知道的，比我們以為的要多。",
    type:        "clue",
    icon:        "💉",
    pickable:    false,
    triggersClue: true,
    clueContent: "案發現場電箱蓋上發現針頭注射痕跡，排列規律，疑似有人利用特定注射方式造成監控系統短暫中斷。此技術需要具備電子與化學的複合知識。",
    requiredAct: 3,
    oneTimeOnly: false,
    position:    "電箱",
  },
];
