import type { SceneItem } from "./types";

export const FOGGY_DOCK_ITEMS: SceneItem[] = [
  {
    id:          "zhuanghe",
    name:        "莊河",
    shortDesc:   "碼頭茶攤的人",
    inspectText: "他坐在茶攤的折疊椅上，沒有客人的時候也在坐。茶壺是舊的，桌上擺著幾個塑膠杯，沒有一個是乾淨的。他的眼神沿著碼頭邊緣緩慢移動，不是在看風景，是在看什麼東西有沒有出現，或者什麼東西有沒有消失。你走過去，他遞給你一杯茶，說：「坐，不急。」",
    type:        "npc",
    icon:        "🧓",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "茶攤",
    npcId:       "zhuanghe",
  },
  {
    id:          "taosheng",
    name:        "陶生",
    shortDesc:   "工地忙碌的人",
    inspectText: "他在一輛貨車旁邊，手上拿著夾板，和另一個人核對什麼清單。工作服是橘色的，袖子捲起來，腕上有一個不太搭調的金屬錶。你注意到他的清單比他應該需要的更厚，而且有一些頁面是被訂起來的，普通的貨物清單不需要這樣。他發現你在看他，走開了。",
    type:        "npc",
    icon:        "👷",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "貨車旁",
    npcId:       "taosheng",
  },
  {
    id:          "fishing_boat",
    name:        "停泊的漁船",
    shortDesc:   "不像漁船的漁船",
    inspectText: "船名的漆已經剝落，辨不出原本的字。甲板是乾的，但繩子是濕的，說明不久前才靠岸。漁網收在一邊，但折疊的方式是機械式的，不是漁民習慣的手法。船底有一條不起眼的焊接縫，顏色比船身其他部分新，像是某個空間被封起來，又重新打開過。",
    type:        "environment",
    icon:        "⛵",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "二號泊位",
  },
  {
    id:          "forced_lock",
    name:        "被撬過的倉庫門鎖",
    shortDesc:   "撬過的鎖",
    inspectText: "倉庫的掛鎖外表看起來是關著的，但你用兩根手指就能把它拉開，插銷根本沒有咬進去。鎖環上有幾道新的刮痕，工具留下的，幹淨俐落，有技術的人做的。倉庫門口的地面有積水，積水裡有被踩亂的痕跡，至少兩個人走過，最近的一次不超過十二小時前。",
    type:        "clue",
    icon:        "🔓",
    pickable:    false,
    triggersClue: true,
    clueContent: "霧港碼頭倉庫掛鎖遭專業工具撬過，積水地面顯示十二小時內有至少兩人進入。倉庫編號 W-07，名義登記為空倉。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "W-07 倉庫",
  },
  {
    id:          "dock_chain",
    name:        "碼頭鏈條",
    shortDesc:   "非標準鏈條",
    inspectText: "這條鏈條比碼頭通常用的更重，材質也不同，像是工業用途，而不是海事標準。固定的方式很奇怪，一端扣在標準的碼頭環上，另一端扣在一個臨時焊接的鐵釘上，位置在水面下方約三十公分。霧很濃，你無法看清楚鏈條那一端在水底連著什麼。",
    type:        "environment",
    icon:        "⛓️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "碼頭邊緣",
  },
  {
    id:          "wet_notebook",
    name:        "濕透的筆記本",
    shortDesc:   "泡過水的本子",
    inspectText: "在一個防水布下面，幾乎被一個木箱壓住。整本都濕透了，但有幾頁因為壓在裡面保留了一些字跡。能看清楚的只有一頁：一張手繪的碼頭平面圖，上面有幾個被圓圈標記的位置，其中一個圈比其他的都大，旁邊寫了一個日期，是下周三。",
    type:        "item",
    icon:        "📓",
    pickable:    true,
    inventoryEntry: {
      itemId:      "wet_notebook",
      name:        "受潮的筆記本",
      description: "濕透的筆記本，殘存一頁手繪碼頭平面圖，標記了多個位置，最大的圓圈旁注記著下周三的日期。筆跡細小精確，像是工程或情報背景的人所畫。",
      icon:        "📓",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "防水布下",
  },
  {
    id:          "rusty_key",
    name:        "生鏽的鑰匙",
    shortDesc:   "鏽蝕的舊鑰匙",
    inspectText: "在積水裡半沉著，如果不是陽光從霧裡透出來的角度剛好，你根本不會注意到。鑰匙的形狀是老式的倉庫鑰匙，但規格比標準的大。鑰匙柄上有一個刻字，因為生鏽只能辨認出一個數字：7。這個碼頭上有一個 W-07 的倉庫。",
    type:        "item",
    icon:        "🗝️",
    pickable:    true,
    inventoryEntry: {
      itemId:      "rusty_key_w07",
      name:        "生鏽的 W-07 鑰匙",
      description: "老式倉庫鑰匙，鏽蝕嚴重，柄上刻有數字「7」。規格與霧港碼頭 W-07 倉庫的原始門鎖吻合。",
      icon:        "🗝️",
    },
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "積水地面",
  },
  {
    id:          "liquid_stain",
    name:        "不明液體痕跡",
    shortDesc:   "地面暗色痕跡",
    inspectText: "在靠近水邊的木板縫隙裡，有一條細長的深色痕跡，不是海水，不是油，黏度介於兩者之間。用手指碰一下，有一點輕微的化學氣味，像是之前在案發現場聞到過的那種甜，但更濃一點。液體的走向是從陸地往水邊，沒有逆流的可能，說明它是被帶過來的，不是漲潮留下的。",
    type:        "clue",
    icon:        "💧",
    pickable:    false,
    triggersClue: true,
    clueContent: "霧港碼頭木板縫發現不明化學液體痕跡，氣味與案發現場殘留物相似，但濃度更高。液體走向由陸地往水邊，疑似在此地轉移物品或人員。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "碼頭木板",
  },
  {
    id:          "drag_marks",
    name:        "拖行痕跡",
    shortDesc:   "地面拖痕",
    inspectText: "在倉庫出口到碼頭邊緣之間，木板上有兩道平行的淺痕。間距大約肩寬，深度均勻，說明被拖動的東西重量是平均分佈的，不是一個角。痕跡在水邊突然消失，下方是三公尺的深水。今晚的潮汐是退潮，方向是往外。",
    type:        "clue",
    icon:        "〰️",
    pickable:    false,
    triggersClue: true,
    clueContent: "霧港碼頭倉庫出口至水邊發現拖行痕跡，兩道平行、間距肩寬，痕跡在深水處消失。結合退潮方向判斷，有重型物體在近期被移入水中。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "碼頭木板",
  },
  {
    id:          "fog_smell",
    name:        "霧中的氣味",
    shortDesc:   "說不清楚的氣味",
    inspectText: "你站在碼頭邊，霧把燈光壓成一個模糊的光圈。這時候空氣裡有一種奇怪的氣味，鹽之外的，不是海洋，不是柴油，不是魚。是一種很古老的、讓人想到地下室或者密閉空間的氣味。它停留了幾秒鐘，然後被海風稀釋乾淨。你記住了，但你沒辦法說清楚它是什麼。",
    type:        "environment",
    icon:        "🌫️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "碼頭邊緣",
  },
];
