import type { SceneItem } from "./types";

export const LIN_LAB_ITEMS: SceneItem[] = [
  {
    id:          "linzhixia_lab",
    name:        "林知夏",
    shortDesc:   "在記錄什麼的研究者",
    inspectText: "她在白板前站著，但她沒有在寫——她在看。白板上的東西你從這個距離看不清楚，只看得出來有很多數字和一條線，那條線從左邊延伸到最右邊，中間有幾個點。她聽到你進來的聲音，轉頭，眼睛亮的方式和其他人不太一樣——不是驚訝，是一種找到了什麼的亮度。",
    type:        "npc",
    icon:        "👩‍🔬",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "實驗室白板前",
    npcId:       "linzhixia",
  },
  {
    id:          "hanzhuo_lab",
    name:        "韓卓",
    shortDesc:   "來核對數據的鑑識人員",
    inspectText: "他坐在實驗台邊緣，手裡拿著一份林知夏的列印資料，和他自己帶來的文件比對。他不喜歡在這裡——你從他坐著的方式就看出來了，那種隨時要站起來走人的坐法。他看了你一眼，沒有說話，繼續低頭看那兩份紙。他的手指在某一行停了比較長的時間。",
    type:        "npc",
    icon:        "🧑‍🔬",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "實驗台邊",
    npcId:       "hanzhuo",
  },
  {
    id:          "research_whiteboard",
    name:        "研究白板",
    shortDesc:   "密密麻麻的時序圖",
    inspectText: "走近了才看清楚：那條線是時間軸，每個點是一個日期，日期旁邊標著縮寫——你認出了其中幾個是人名的縮寫。時間軸的右端是一個打了圓圈的日期，旁邊寫著「L.Y.↑」。你查了一下，L.Y. 是林淵的縮寫，那個日期是他覺醒被記錄在案的日期。在那個日期之後，其他的縮寫都停了，沒有後續的標記。",
    type:        "environment",
    icon:        "📊",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "白板牆",
  },
  {
    id:          "phase2_journal",
    name:        "第二相體觀察日誌",
    shortDesc:   "手寫研究紀錄",
    inspectText: "封面用鉛筆寫著「Personal — Do Not Process」，英文，不是中文，像是在提醒自己。日誌裡用的是一種林知夏自己設計的縮寫系統，前幾頁你幾乎看不懂。但翻到後面，有幾段她切換回了正常的書寫——應該是緊急記錄，顧不上系統了。你從那幾段裡拼出了一件事：她認為覺醒不是隨機的，是被誘發的。",
    type:        "item",
    icon:        "📓",
    pickable:    true,
    inventoryEntry: {
      itemId:      "phase2_journal_item",
      name:        "林知夏的觀察日誌",
      description: "以個人縮寫系統撰寫的第二相體研究日誌。緊急記錄段落清晰：林知夏相信覺醒並非自發，而是被特定條件「誘發」。記錄涵蓋多名已失蹤者。",
      icon:        "📓",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "研究桌",
  },
  {
    id:          "tissue_samples",
    name:        "組織樣本架",
    shortDesc:   "冷藏架上的樣本管",
    inspectText: "每個樣本管上都有標籤，標籤上的編號你查不到對應的姓名——但旁邊有一個小紙條，上面有兩列，左邊是編號，右邊是人名的縮寫。你數了一下，十四個編號，十四個縮寫。你把那張紙條拍了下來，然後放回原位。其中有幾個編號的樣本管是空的。",
    type:        "clue",
    icon:        "🧫",
    pickable:    false,
    triggersClue: true,
    clueContent: "實驗室冷藏架有十四組組織樣本，對照紙條可確認對應十四名失蹤者。部分樣本管已空，說明林知夏在失蹤案發生之前或期間已掌握這批人的生物樣本。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "冷藏樣本架",
  },
  {
    id:          "encrypted_drive",
    name:        "加密硬碟",
    shortDesc:   "插在電腦側邊的外接硬碟",
    inspectText: "黑色的小硬碟，插著但螢幕是黑的。你按了一下電腦，螢幕亮了，上面顯示一個密碼輸入介面。背景是全黑，輸入框旁邊有一行灰色的字：「ERROR_LOG_03 — RESTRICTED」。你沒有密碼。但硬碟外殼上有一個貼紙，幾乎跟外殼同色，用力看才看到：兩個字，「K.L.」。你在別的地方見過這個縮寫。",
    type:        "item",
    icon:        "💾",
    pickable:    true,
    inventoryEntry: {
      itemId:      "encrypted_drive_item",
      name:        "加密外接硬碟",
      description: "標示「ERROR_LOG_03 — RESTRICTED」的密碼鎖定硬碟。外殼有幾乎不可見的「K.L.」貼紙標記——與陳姐麵館角落外套的縮寫相符。",
      icon:        "💾",
    },
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "電腦桌",
  },
  {
    id:          "lab_incident_report",
    name:        "實驗事故紀錄",
    shortDesc:   "夾在雜誌裡的一頁文件",
    inspectText: "不是刻意收起來的，更像是塞進去然後忘了。文件的標題是「Phase Resonance Incident — Internal Review」，日期是林淵覺醒被記錄的前兩週。正文描述了一次「非預期的相位共鳴反應」，其中有三個人員被標記為「需持續監控」。這三個人的姓名被用白色貼紙蓋住，但貼紙貼得不夠緊，你把一個角掀起來，看到了第一個名字。",
    type:        "clue",
    icon:        "📑",
    pickable:    false,
    triggersClue: true,
    clueContent: "實驗室事故報告記錄林淵覺醒前兩週發生「非預期相位共鳴」，三名相關人員被列入「持續監控」名單。報告為機構內部文件，出現在林知夏實驗室，說明她的研究與機構實驗存在直接關聯。",
    requiredAct: 3,
    oneTimeOnly: false,
    position:    "期刊架",
  },
];
