import type { SceneItem } from "./types";

export const MEDICAL_CENTER_ITEMS: SceneItem[] = [
  {
    id:          "yushuang_ward",
    name:        "余霜",
    shortDesc:   "當班護士",
    inspectText: "她穿著白色護士服站在護理站外側，手裡夾著幾份表格，但她沒有在看。她的視線越過你，落在某個你不在的地方。你走過去的時候，她轉向你，微笑，那個笑的幅度剛剛好——不多，不少，像是有人教過她怎麼讓人覺得安心。你覺得安心，然後你覺得不對勁。",
    type:        "npc",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "護理站外側走廊",
    npcId:       "yushuang",
  },
  {
    id:          "it_waiting",
    name:        "謝先生",
    shortDesc:   "候診區的等待者",
    inspectText: "他坐在候診區最角落的位置，背靠牆，手放在膝蓋上。他沒有拿任何東西，沒有看手機，沒有打哈欠。他只是坐著，以一種讓你說不出為什麼不對的方式坐著。你走過去的時候，他先你一步轉過來看你，好像他早就知道你的下一個方向。",
    type:        "npc",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "候診區角落",
    npcId:       "it",
  },
  {
    id:          "lin_yuan_room",
    name:        "林淵的舊病房",
    shortDesc:   "310號病房",
    inspectText: "門上的號碼是310，床是空的。牆上有幾個地方顏色跟其他地方不一樣——有人重新刷過漆，但刷的範圍太精準，像是在蓋什麼東西，不像是日常維護。窗邊的鐵架上還掛著一個點滴架，歪著，沒有人扶正它。你站在門口，沒有進去。你不確定為什麼，但你覺得那扇門一旦關上就不容易再打開。",
    type:        "environment",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "三樓走廊盡頭",
  },
  {
    id:          "medical_files",
    name:        "病歷檔案",
    shortDesc:   "部分被調閱過的記錄",
    inspectText: "護理站的檔案架上，大部分的夾子都是整齊的。有一個位置是空的，抽出來又放回去的痕跡，放的時候方向轉了半圈。你找到那個夾子，翻開，內頁有幾個日期的診察記錄被貼上白色修正貼——不是整張蓋掉，是針對性地遮住某幾行。遮住的行數剛好是十四行。",
    type:        "clue",
    icon:        "▣",
    pickable:    false,
    triggersClue: true,
    clueContent: "醫院病歷檔案中有記錄被針對性遮蓋，共十四行——與失蹤人數相符。檔案被調閱後未完全復位，說明有人近期取走或修改了特定日期的診察紀錄。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "護理站檔案架",
  },
  {
    id:          "phase2_test_kit",
    name:        "相位偏移測試套組",
    shortDesc:   "醫療廢棄物箱旁的器材",
    inspectText: "放在走廊角落廢棄物箱旁邊，已經開封，但沒有被丟進去。套組裡的試紙用掉了三份，還有兩份沒用。包裝上的有效期限是本月底，說明這是最近才用的。這種套組通常是醫院正式採購，不會出現在走廊。你把它翻過來，背面有人用鉛筆寫了一串數字：像是識別碼，也像是病歷號碼。",
    type:        "item",
    icon:        "▣",
    pickable:    true,
    inventoryEntry: {
      itemId:      "phase2_test_kit_item",
      name:        "相位偏移測試套組（已開封）",
      description: "醫院走廊發現的開封測試套組，三份試紙已使用，背面鉛筆手寫識別碼。非正常廢棄流程，疑為非官方測試使用。",
      icon:        "▣",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "走廊角落",
  },
  {
    id:          "nurse_station_log",
    name:        "護理站值班紀錄",
    shortDesc:   "夜班手寫交班紀錄",
    inspectText: "交班紀錄通常是例行公事，沒有人會仔細看。你仔細看了。第十四號案發生那晚，夜班護士的簽名欄有兩個名字：一個是正常的值班護士，另一個——簽名筆跡特別規整，不像是手寫的，更像是臨摹過的。那個名字你查過，不在醫院的正式員工名單裡。",
    type:        "clue",
    icon:        "▣",
    pickable:    false,
    triggersClue: true,
    clueContent: "案發當晚護理站交班紀錄出現一個不存在於醫院正式員工名冊的簽名，筆跡異常規整，疑為偽造。當晚醫院有不明人員在場。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "護理站",
  },
  {
    id:          "isolation_ward",
    name:        "隔離病房走廊",
    shortDesc:   "不對外開放的區域",
    inspectText: "門上貼著「限制進入」的標示，但門是虛掩的。走廊比其他地方暗，燈管有一半是關著的。你推開門，空氣更冷，有一種像是低頻聲音的感覺，說是聲音又太輕，只是一種壓在耳膜上的感覺。最裡面的那個病房裡有人影，沒有動。你看了幾秒，那個人影也沒有動。你把門帶上，出來了。",
    type:        "environment",
    icon:        "▣",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "三樓側翼走廊",
  },
];
