import type { SceneItem } from "./types";

export const PRECINCT_9_ITEMS: SceneItem[] = [
  {
    id:          "yushuang",
    name:        "余霜",
    shortDesc:   "走廊等待的人",
    inspectText: "她站在走廊的等候椅旁邊，但沒有坐下。制服的扣子扣到最上面一顆，姿勢是那種讓你感覺她在這裡是有任務的，而不是在等什麼事情發生。她看到你的時候，表情沒有變化，只是輕輕點了一下頭。那個點頭裡面有一些東西是警告，也有一些東西是提醒，你不確定哪個成分更多。",
    type:        "npc",
    icon:        "👮‍♀️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "走廊",
    npcId:       "yushuang",
  },
  {
    id:          "it",
    name:        "謝先生",
    shortDesc:   "靠牆坐著的人",
    inspectText: "他在等候區最裡面的椅子上，背靠著牆，雙腿交叉，看起來在等一件他已經等了很久的事。衣服是便服，但坐的方式不像普通人，腰背挺直，手放在大腿上，注意力是開的，不是休息，是在觀察。他的眼神掃過你，停了半秒，然後繼續看別的地方。那半秒夠他記住你所有重要的特徵。",
    type:        "npc",
    icon:        "🧑",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "等候區",
    npcId:       "it",
  },
  {
    id:          "case_board",
    name:        "案件公告板",
    shortDesc:   "佈滿文件的板子",
    inspectText: "公告板掛在走廊盡頭，理論上是公開的，但在這個角度，你能看見的只有上半部。貼著幾份通緝告示，一份失蹤人口的名單更新，還有一個空白的區域，有幾個圖釘的洞，說明之前有東西被拆下來了。拆下來的東西，和在這裡的東西，哪些是真正公開的，哪些是讓人看到的——你開始理解，這兩件事不一樣。",
    type:        "environment",
    icon:        "📋",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "走廊盡頭",
  },
  {
    id:          "interrogation_window",
    name:        "審訊室窗戶",
    shortDesc:   "單向玻璃後面",
    inspectText: "窗戶是單向玻璃，你在外面看不見裡面。但有一道細細的光從門縫透出來，說明裡面開著燈。你把耳朵靠近門，能聽到說話聲，低沉，斷續，一個人在說，另一個人很少回答。然後突然安靜了，安靜了大概三十秒，之後你聽到椅子挪動的聲音。有人站起來了。",
    type:        "environment",
    icon:        "🪟",
    pickable:    false,
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "審訊室走廊",
  },
  {
    id:          "locked_cabinet",
    name:        "鎖住的檔案櫃",
    shortDesc:   "三層鎖的鐵櫃",
    inspectText: "灰色鐵皮，三個抽屜，三把鎖，每一把都是不同的型號。這是有意的，不是統一採購的結果，有人在保護裡面的東西免於被一把萬用鑰匙打開。最下層的抽屜縫隙裡有一小段紙張，像是某份文件的角落，被夾住沒有完全進去，上面印著一個機構名稱，你只能看到最後兩個字：「研究」。",
    type:        "environment",
    icon:        "🗄️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "辦公室角落",
  },
  {
    id:          "lost_badge",
    name:        "遺失的警徽",
    shortDesc:   "不屬於這裡的警徽",
    inspectText: "在等候椅下面，被踢到椅腳後方，如果不是你低頭撿起了一份掉落的表格，你根本看不到它。金屬面已經有磨損，編號的地方幾乎看不清楚，但角落的機構縮寫還認得出來。那個縮寫不是第九分局，也不是市警局任何一個公開的部門。",
    type:        "item",
    icon:        "🪪",
    pickable:    true,
    inventoryEntry: {
      itemId:      "police_badge",
      name:        "舊警徽",
      description: "編號已磨損，隸屬單位縮寫為「S.I.U.」——不是第九分局，也不屬於市警局任何公開部門。這個縮寫在公開資料庫裡查不到。",
      icon:        "🪪",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "等候椅下方",
  },
  {
    id:          "note_paper",
    name:        "便箋",
    shortDesc:   "有字的便條紙",
    inspectText: "粘在飲水機旁邊的牆上，上面用很小的字寫了一串數字，下面畫了一條線，線下面是三個漢字，字跡很潦草，你花了幾秒才辨認出來：不要來。你不確定這是給你的，還是給某個在你之前到達這裡的人的。但它就貼在那裡，粘得很牢，像是放在那裡等一個特定的人看見。",
    type:        "item",
    icon:        "📄",
    pickable:    true,
    inventoryEntry: {
      itemId:      "precinct_note",
      name:        "第九分局便箋",
      description: "寫有一串數字和「不要來」三字的便條，數字格式像是日期或案件編號。貼在飲水機旁，像是等待特定人閱讀。",
      icon:        "📄",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "飲水機旁",
  },
  {
    id:          "torn_document",
    name:        "被撕毀的文件碎片",
    shortDesc:   "垃圾桶邊的碎紙",
    inspectText: "垃圾桶旁邊的地板上，有幾片碎紙，撕得很碎，像是有人試圖在有人進來之前處理掉什麼東西。你把幾片拼在一起，能拼出一個日期，一個地名，還有一個名字的前兩個字：「林知」——你認識這個名字。這份文件，和你已經知道的事情之間，有某種連結你還沒看清楚。",
    type:        "clue",
    icon:        "📃",
    pickable:    false,
    triggersClue: true,
    clueContent: "第九分局垃圾桶旁發現被撕碎的文件，拼湊後可見一個日期、一個地名，以及名字「林知」——與林知夏相符。文件似乎是某份內部調查紀錄的一部分。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "垃圾桶旁",
  },
  {
    id:          "erased_whiteboard",
    name:        "白板擦掉的字跡",
    shortDesc:   "白板殘留痕跡",
    inspectText: "白板被擦過，但擦板的力道不均勻，在斜光下還能看到一些殘影。能辨認出的有一個問號，一個箭頭，和幾個字的下半部。其中有一個字的下半部看起來像「蹤」，另一個像「藥」。整個排列像是某種時間線或流程圖的中段，頭和尾都被擦乾淨了，留下來的是中間最難理解的部分。",
    type:        "clue",
    icon:        "📊",
    pickable:    false,
    triggersClue: true,
    clueContent: "第九分局白板殘留字跡，斜光下可辨認「蹤」「藥」二字及箭頭符號，排列形式為流程圖，疑為失蹤案調查的內部分析框架，被刻意不完整地清除。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "辦公室白板",
  },
  {
    id:          "flickering_light",
    name:        "走廊閃爍的日光燈",
    shortDesc:   "三秒閃一次的燈",
    inspectText: "走廊最裡面的那盞燈，三秒閃一次，像是一個問句被反覆說起。有人通知過維修部門，工單已經貼在牆上，但沒有人來處理，工單上的日期是三周前。燈的閃爍在這個安靜的等候空間裡讓人想到某種計時，像是有什麼事情正在倒計時，只是你不知道到零的時候會發生什麼。",
    type:        "environment",
    icon:        "💡",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "走廊深處",
  },
];
