import type { SceneItem } from "./types";

export const ZHENGBO_OFFICE_ITEMS: SceneItem[] = [
  {
    id:          "zhengbo_desk",
    name:        "鄭博",
    shortDesc:   "在整理文件的保險調查員",
    inspectText: "他坐在辦公桌後面，但他辦公桌上的文件不像是保險理賠的文件。他在把一疊什麼整理成某種順序，動作有點快，不像平時在麵館的慢。你站在門口，他沒有說請進，但也沒有讓你走。他停下來，把那疊文件翻過去，正面朝下，然後看著你說：「我就知道你會來這裡。」",
    type:        "npc",
    icon:        "🧔",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "辦公桌後方",
    npcId:       "zhengbo",
  },
  {
    id:          "case_files_wall",
    name:        "案件資料牆",
    shortDesc:   "整面牆的釘板",
    inspectText: "你沒見過有人把保險理賠案件整理成這樣的。照片、名字、時間軸、線條——更像刑警在追連環案，不像保險公司在核對文件。你走近看，名字下面有時間，時間下面有地點，地點之間有連線。左下角有一個圓圈，圓圈裡貼著一張照片，照片裡的人在看鏡頭，不在乎有人拍。你不認識那個人，但你記住了那張臉。",
    type:        "environment",
    icon:        "📌",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "辦公室牆面",
  },
  {
    id:          "wife_photo",
    name:        "妻子的照片",
    shortDesc:   "辦公桌角落的相框",
    inspectText: "相框很普通，放在桌角，不顯眼，但放的方式不像裝飾，更像是一個定位點——他工作的時候視線能落到的地方。照片裡的女人在笑，背景是你在別的地方見過的碼頭。你把相框拿起來，背面有人用鉛筆寫了幾個字，已經擦過，但壓痕還在：「找到的時候你不知道你在找什麼。」你不確定這句話是她寫給他的，還是他寫給自己的。",
    type:        "environment",
    icon:        "🖼️",
    pickable:    false,
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: true,
    position:    "辦公桌角落",
  },
  {
    id:          "victim_financial_records",
    name:        "受害者財務記錄",
    shortDesc:   "標著顏色的資料夾",
    inspectText: "資料夾用顏色標記，你猜不透顏色的邏輯，但看了兩份之後你發現了：所有標著紅色的資料夾，裡面都是同一種情況——失蹤者在消失前的一到三個月，突然有一筆大額保險理賠款入帳。不是他們自己辦的，是有人幫他們辦的，辦的人都填的同一個代理人代碼。",
    type:        "clue",
    icon:        "📁",
    pickable:    false,
    triggersClue: true,
    clueContent: "受害者財務記錄顯示：多名失蹤者在消失前一到三個月有不明保險理賠入帳，代理人代碼相同。理賠在失蹤前完成，說明有人預先知道這些人即將失蹤。",
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "書架",
  },
  {
    id:          "insurance_pattern",
    name:        "理賠異常清單",
    shortDesc:   "手寫的統計表",
    inspectText: "用方格紙畫的，幾列幾行，每個交叉點都有數字或縮寫。你花了幾分鐘才理解這張表在說什麼：十四個人，失蹤前的保單類型、理賠金額、受益人——受益人這一欄，有七個人的受益人是同一個名字，一個你查不到的名字。鄭博在那個名字旁邊畫了三個問號，最後那個問號畫得比較重，紙都有點凹進去。",
    type:        "item",
    icon:        "📊",
    pickable:    true,
    inventoryEntry: {
      itemId:      "insurance_anomaly_list",
      name:        "保險理賠異常清單",
      description: "手繪統計表：十四名失蹤者的保單資料，七人受益人為同一不知名者。鄭博標記三個問號，最後一個較深。受益人身份是關鍵未解謎題。",
      icon:        "📊",
    },
    triggersClue: false,
    requiredAct: 1,
    oneTimeOnly: false,
    position:    "辦公桌抽屜",
  },
  {
    id:          "private_investigation_board",
    name:        "私人調查記錄板",
    shortDesc:   "翻轉朝牆的釘板背面",
    inspectText: "釘板的正面是那面案件牆，翻到背面，還有另一層。這一層不像正面那樣有系統，更像是隨手寫下的東西：名字、問題、幾行語氣很急的字。其中有一行是「他知道這是誰幹的——他不說是因為他知道說了以後」，後面沒有繼續寫，像是中途停下來想了一下，然後想清楚了反而沉默了。",
    type:        "clue",
    icon:        "🗂️",
    pickable:    false,
    triggersClue: true,
    clueContent: "鄭博私人記錄板背面顯示他相信有人知道兇手是誰但選擇沉默。未完成的句子暗示他認為說出名字存在危險。鄭博掌握的線索可能超出他公開表明的範圍。",
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "釘板背面",
  },
  {
    id:          "partial_computer_data",
    name:        "電腦殘留資料",
    shortDesc:   "未登出的瀏覽器分頁",
    inspectText: "電腦螢幕還亮著，鄭博走開的時候沒有關。瀏覽器開著幾個分頁：一個是 BTMA 的公開官網，另一個是某個論壇，第三個是一個需要登入的資料庫頁面，登入狀態已失效，但網址列上還有一串參數，裡面有一個詞你能看清楚：「PROC_CASEFILE」。你把網址截圖下來，然後把螢幕調暗。",
    type:        "item",
    icon:        "💻",
    pickable:    true,
    inventoryEntry: {
      itemId:      "computer_residual_data",
      name:        "電腦網址截圖",
      description: "鄭博辦公電腦開啟的資料庫頁面網址，含參數「PROC_CASEFILE」，指向 BTMA 受限資料庫。登入已失效，但網址結構暗示鄭博曾成功存取此資料庫。",
      icon:        "💻",
    },
    triggersClue: false,
    requiredAct: 2,
    oneTimeOnly: false,
    position:    "辦公桌電腦",
  },
];
